language: php
php:
  - 5.5
  - 5.4

notifications:
  slack: jonathansblog:xcTlLtSp7QrTmEjxjH9Jq3bR
  email: false

install:
 - pyrus install http://phptal.org/latest.tar.gz
 - pear config-set auto_discover 1
 - pear install PHP_CodeSniffer
 - git clone git://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
 - phpenv rehash
 
script:
 - phpcs --extensions=php --standard=$(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress .