language: php

php:
- '7.0'
- '5.6'
- '5.5'
- '5.4'

sudo: false


before_script:
- composer self-update
- composer --version
- THEME_SLUG=$(pwd)
- cd /tmp/
- git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
- git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
- cd phpcs
- scripts/phpcs --config-set installed_paths ../wpcs
- cd "$THEME_SLUG"
- phpenv rehash

script:

- /tmp/phpcs/scripts/phpcs -p -s -v -n --standard=ruleset.xml --extensions=php .

notifications:
  slack: jonathansblog:xcTlLtSp7QrTmEjxjH9Jq3bR
  email: false
